(cl:defpackage advanced-msg
  (:use )
  (:export
   "<FIRST_ACTIONACTION>"
   "FIRST_ACTIONACTION"
   "<FIRST_ACTIONACTIONFEEDBACK>"
   "FIRST_ACTIONACTIONFEEDBACK"
   "<FIRST_ACTIONACTIONGOAL>"
   "FIRST_ACTIONACTIONGOAL"
   "<FIRST_ACTIONACTIONRESULT>"
   "FIRST_ACTIONACTIONRESULT"
   "<FIRST_ACTIONFEEDBACK>"
   "FIRST_ACTIONFEEDBACK"
   "<FIRST_ACTIONGOAL>"
   "FIRST_ACTIONGOAL"
   "<FIRST_ACTIONRESULT>"
   "FIRST_ACTIONRESULT"
  ))

