; Auto-generated. Do not edit!


(cl:in-package advanced-msg)


;//! \htmlinclude first_actionResult.msg.html

(cl:defclass <first_actionResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass first_actionResult (<first_actionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <first_actionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'first_actionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name advanced-msg:<first_actionResult> is deprecated: use advanced-msg:first_actionResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <first_actionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader advanced-msg:result-val is deprecated.  Use advanced-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <first_actionResult>) ostream)
  "Serializes a message object of type '<first_actionResult>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <first_actionResult>) istream)
  "Deserializes a message object of type '<first_actionResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<first_actionResult>)))
  "Returns string type for a message object of type '<first_actionResult>"
  "advanced/first_actionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'first_actionResult)))
  "Returns string type for a message object of type 'first_actionResult"
  "advanced/first_actionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<first_actionResult>)))
  "Returns md5sum for a message object of type '<first_actionResult>"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'first_actionResult)))
  "Returns md5sum for a message object of type 'first_actionResult"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<first_actionResult>)))
  "Returns full string definition for message of type '<first_actionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#最终结果  y~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'first_actionResult)))
  "Returns full string definition for message of type 'first_actionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#最终结果  y~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <first_actionResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <first_actionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'first_actionResult
    (cl:cons ':result (result msg))
))
