; Auto-generated. Do not edit!


(cl:in-package advanced-msg)


;//! \htmlinclude first_actionGoal.msg.html

(cl:defclass <first_actionGoal> (roslisp-msg-protocol:ros-message)
  ((num
    :reader num
    :initarg :num
    :type cl:integer
    :initform 0))
)

(cl:defclass first_actionGoal (<first_actionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <first_actionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'first_actionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name advanced-msg:<first_actionGoal> is deprecated: use advanced-msg:first_actionGoal instead.")))

(cl:ensure-generic-function 'num-val :lambda-list '(m))
(cl:defmethod num-val ((m <first_actionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader advanced-msg:num-val is deprecated.  Use advanced-msg:num instead.")
  (num m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <first_actionGoal>) ostream)
  "Serializes a message object of type '<first_actionGoal>"
  (cl:let* ((signed (cl:slot-value msg 'num)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <first_actionGoal>) istream)
  "Deserializes a message object of type '<first_actionGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'num) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<first_actionGoal>)))
  "Returns string type for a message object of type '<first_actionGoal>"
  "advanced/first_actionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'first_actionGoal)))
  "Returns string type for a message object of type 'first_actionGoal"
  "advanced/first_actionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<first_actionGoal>)))
  "Returns md5sum for a message object of type '<first_actionGoal>"
  "54b3c80efd6fae6e6ffff8a4b9facd69")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'first_actionGoal)))
  "Returns md5sum for a message object of type 'first_actionGoal"
  "54b3c80efd6fae6e6ffff8a4b9facd69")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<first_actionGoal>)))
  "Returns full string definition for message of type '<first_actionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#目标值  x~%int32 num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'first_actionGoal)))
  "Returns full string definition for message of type 'first_actionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#目标值  x~%int32 num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <first_actionGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <first_actionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'first_actionGoal
    (cl:cons ':num (num msg))
))
