// Generated by gencpp from file serverclient/addints.msg
// DO NOT EDIT!


#ifndef SERVERCLIENT_MESSAGE_ADDINTS_H
#define SERVERCLIENT_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <serverclient/addintsRequest.h>
#include <serverclient/addintsResponse.h>


namespace serverclient
{

struct addints
{

typedef addintsRequest Request;
typedef addintsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addints
} // namespace serverclient


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::serverclient::addints > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::serverclient::addints&) { return value(); }
};

template<>
struct DataType< ::serverclient::addints > {
  static const char* value()
  {
    return "serverclient/addints";
  }

  static const char* value(const ::serverclient::addints&) { return value(); }
};


// service_traits::MD5Sum< ::serverclient::addintsRequest> should match
// service_traits::MD5Sum< ::serverclient::addints >
template<>
struct MD5Sum< ::serverclient::addintsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::serverclient::addints >::value();
  }
  static const char* value(const ::serverclient::addintsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::serverclient::addintsRequest> should match
// service_traits::DataType< ::serverclient::addints >
template<>
struct DataType< ::serverclient::addintsRequest>
{
  static const char* value()
  {
    return DataType< ::serverclient::addints >::value();
  }
  static const char* value(const ::serverclient::addintsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::serverclient::addintsResponse> should match
// service_traits::MD5Sum< ::serverclient::addints >
template<>
struct MD5Sum< ::serverclient::addintsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::serverclient::addints >::value();
  }
  static const char* value(const ::serverclient::addintsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::serverclient::addintsResponse> should match
// service_traits::DataType< ::serverclient::addints >
template<>
struct DataType< ::serverclient::addintsResponse>
{
  static const char* value()
  {
    return DataType< ::serverclient::addints >::value();
  }
  static const char* value(const ::serverclient::addintsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVERCLIENT_MESSAGE_ADDINTS_H
