// Generated by gencpp from file advanced/first_actionResult.msg
// DO NOT EDIT!


#ifndef ADVANCED_MESSAGE_FIRST_ACTIONRESULT_H
#define ADVANCED_MESSAGE_FIRST_ACTIONRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace advanced
{
template <class ContainerAllocator>
struct first_actionResult_
{
  typedef first_actionResult_<ContainerAllocator> Type;

  first_actionResult_()
    : result(0)  {
    }
  first_actionResult_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::advanced::first_actionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::advanced::first_actionResult_<ContainerAllocator> const> ConstPtr;

}; // struct first_actionResult_

typedef ::advanced::first_actionResult_<std::allocator<void> > first_actionResult;

typedef boost::shared_ptr< ::advanced::first_actionResult > first_actionResultPtr;
typedef boost::shared_ptr< ::advanced::first_actionResult const> first_actionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::advanced::first_actionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::advanced::first_actionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::advanced::first_actionResult_<ContainerAllocator1> & lhs, const ::advanced::first_actionResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::advanced::first_actionResult_<ContainerAllocator1> & lhs, const ::advanced::first_actionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace advanced

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::advanced::first_actionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::advanced::first_actionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::advanced::first_actionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::advanced::first_actionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::advanced::first_actionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::advanced::first_actionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::advanced::first_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::advanced::first_actionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::advanced::first_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "advanced/first_actionResult";
  }

  static const char* value(const ::advanced::first_actionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::advanced::first_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#最终结果  y\n"
"int32 result\n"
;
  }

  static const char* value(const ::advanced::first_actionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::advanced::first_actionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct first_actionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::advanced::first_actionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::advanced::first_actionResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADVANCED_MESSAGE_FIRST_ACTIONRESULT_H
