// Generated by gencpp from file advanced/first_actionFeedback.msg
// DO NOT EDIT!


#ifndef ADVANCED_MESSAGE_FIRST_ACTIONFEEDBACK_H
#define ADVANCED_MESSAGE_FIRST_ACTIONFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace advanced
{
template <class ContainerAllocator>
struct first_actionFeedback_
{
  typedef first_actionFeedback_<ContainerAllocator> Type;

  first_actionFeedback_()
    : progress_bar(0.0)  {
    }
  first_actionFeedback_(const ContainerAllocator& _alloc)
    : progress_bar(0.0)  {
  (void)_alloc;
    }



   typedef double _progress_bar_type;
  _progress_bar_type progress_bar;





  typedef boost::shared_ptr< ::advanced::first_actionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::advanced::first_actionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct first_actionFeedback_

typedef ::advanced::first_actionFeedback_<std::allocator<void> > first_actionFeedback;

typedef boost::shared_ptr< ::advanced::first_actionFeedback > first_actionFeedbackPtr;
typedef boost::shared_ptr< ::advanced::first_actionFeedback const> first_actionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::advanced::first_actionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::advanced::first_actionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::advanced::first_actionFeedback_<ContainerAllocator1> & lhs, const ::advanced::first_actionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.progress_bar == rhs.progress_bar;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::advanced::first_actionFeedback_<ContainerAllocator1> & lhs, const ::advanced::first_actionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace advanced

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::advanced::first_actionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::advanced::first_actionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::advanced::first_actionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::advanced::first_actionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::advanced::first_actionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::advanced::first_actionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::advanced::first_actionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac7532a8a8f0d2be4f5284d94fee2d59";
  }

  static const char* value(const ::advanced::first_actionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac7532a8a8f0d2beULL;
  static const uint64_t static_value2 = 0x4f5284d94fee2d59ULL;
};

template<class ContainerAllocator>
struct DataType< ::advanced::first_actionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "advanced/first_actionFeedback";
  }

  static const char* value(const ::advanced::first_actionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::advanced::first_actionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#连续反馈  feedback\n"
"float64 progress_bar\n"
"\n"
;
  }

  static const char* value(const ::advanced::first_actionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::advanced::first_actionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progress_bar);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct first_actionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::advanced::first_actionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::advanced::first_actionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "progress_bar: ";
    Printer<double>::stream(s, indent + "  ", v.progress_bar);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADVANCED_MESSAGE_FIRST_ACTIONFEEDBACK_H
