// Generated by gencpp from file advanced/first_actionGoal.msg
// DO NOT EDIT!


#ifndef ADVANCED_MESSAGE_FIRST_ACTIONGOAL_H
#define ADVANCED_MESSAGE_FIRST_ACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace advanced
{
template <class ContainerAllocator>
struct first_actionGoal_
{
  typedef first_actionGoal_<ContainerAllocator> Type;

  first_actionGoal_()
    : num(0)  {
    }
  first_actionGoal_(const ContainerAllocator& _alloc)
    : num(0)  {
  (void)_alloc;
    }



   typedef int32_t _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::advanced::first_actionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::advanced::first_actionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct first_actionGoal_

typedef ::advanced::first_actionGoal_<std::allocator<void> > first_actionGoal;

typedef boost::shared_ptr< ::advanced::first_actionGoal > first_actionGoalPtr;
typedef boost::shared_ptr< ::advanced::first_actionGoal const> first_actionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::advanced::first_actionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::advanced::first_actionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::advanced::first_actionGoal_<ContainerAllocator1> & lhs, const ::advanced::first_actionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::advanced::first_actionGoal_<ContainerAllocator1> & lhs, const ::advanced::first_actionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace advanced

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::advanced::first_actionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::advanced::first_actionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::advanced::first_actionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::advanced::first_actionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::advanced::first_actionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::advanced::first_actionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::advanced::first_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54b3c80efd6fae6e6ffff8a4b9facd69";
  }

  static const char* value(const ::advanced::first_actionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54b3c80efd6fae6eULL;
  static const uint64_t static_value2 = 0x6ffff8a4b9facd69ULL;
};

template<class ContainerAllocator>
struct DataType< ::advanced::first_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "advanced/first_actionGoal";
  }

  static const char* value(const ::advanced::first_actionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::advanced::first_actionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#目标值  x\n"
"int32 num\n"
;
  }

  static const char* value(const ::advanced::first_actionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::advanced::first_actionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct first_actionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::advanced::first_actionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::advanced::first_actionGoal_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADVANCED_MESSAGE_FIRST_ACTIONGOAL_H
