// Generated by gencpp from file talklisten/Person.msg
// DO NOT EDIT!


#ifndef TALKLISTEN_MESSAGE_PERSON_H
#define TALKLISTEN_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace talklisten
{
template <class ContainerAllocator>
struct Person_
{
  typedef Person_<ContainerAllocator> Type;

  Person_()
    : name()
    , age(0)
    , height(0.0)
    , accounts(0)  {
    }
  Person_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , height(0.0)
    , accounts(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int32_t _age_type;
  _age_type age;

   typedef float _height_type;
  _height_type height;

   typedef int32_t _accounts_type;
  _accounts_type accounts;





  typedef boost::shared_ptr< ::talklisten::Person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::talklisten::Person_<ContainerAllocator> const> ConstPtr;

}; // struct Person_

typedef ::talklisten::Person_<std::allocator<void> > Person;

typedef boost::shared_ptr< ::talklisten::Person > PersonPtr;
typedef boost::shared_ptr< ::talklisten::Person const> PersonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::talklisten::Person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::talklisten::Person_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::talklisten::Person_<ContainerAllocator1> & lhs, const ::talklisten::Person_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.height == rhs.height &&
    lhs.accounts == rhs.accounts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::talklisten::Person_<ContainerAllocator1> & lhs, const ::talklisten::Person_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace talklisten

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::talklisten::Person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::talklisten::Person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::talklisten::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::talklisten::Person_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::talklisten::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::talklisten::Person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::talklisten::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e04843c1d2645fee4293247734542c2";
  }

  static const char* value(const ::talklisten::Person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e04843c1d2645feULL;
  static const uint64_t static_value2 = 0xe4293247734542c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::talklisten::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "talklisten/Person";
  }

  static const char* value(const ::talklisten::Person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::talklisten::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int32 age\n"
"float32 height\n"
"int32 accounts\n"
;
  }

  static const char* value(const ::talklisten::Person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::talklisten::Person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.height);
      stream.next(m.accounts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::talklisten::Person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::talklisten::Person_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int32_t>::stream(s, indent + "  ", v.age);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "accounts: ";
    Printer<int32_t>::stream(s, indent + "  ", v.accounts);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TALKLISTEN_MESSAGE_PERSON_H
